/* =========================================================
   SHEGLAM PK — static site generator
   Pre-renders every page (chrome + product grids) so the site
   is fully readable with JavaScript disabled, then writes
   sitemap.xml and robots.txt.

   Run:  node build.js
   ========================================================= */
const fs = require("fs");
const path = require("path");

const D = require("./data/catalog.js");
const T = require("./data/templates.js");
const CONTENT = require("./src/content.js");

const { SITE, CATEGORIES, PRODUCTS, COLLECTIONS, PROMOS, FEEDS, money } = D;
const { esc, icon, brandIcon, card, stars } = T;

const ROOT = __dirname;
const OUT_PRODUCT = path.join(ROOT, "product");
/* Emptied on every build. Generating over the top of the previous run
   left pages for products that had been unpublished or archived: they
   were gone from the grid but still served on their own URL, and still
   listed in the sitemap. A product page must not outlive its product. */
fs.rmSync(OUT_PRODUCT, { recursive: true, force: true });
fs.mkdirSync(OUT_PRODUCT, { recursive: true });

const FONT = "https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap";

/* Drop your logo artwork at assets/img/logo.png and it replaces the text
   wordmark everywhere, automatically. */
const HAS_LOGO = fs.existsSync(path.join(ROOT, "assets", "img", "logo.png"));

const FAVICON =
  "data:image/svg+xml," +
  encodeURIComponent(
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#e83e70"/><path fill="#fff" d="M32 12c0 11 9 20 20 20-11 0-20 9-20 20 0-11-9-20-20-20 11 0 20-9 20-20Z"/></svg>`
  );

/* Products live in data/products.json (admin-editable). The browser cannot
   require JSON, so emit a tiny script that hands it the same array. */
fs.writeFileSync(
  path.join(ROOT, "data", "products.js"),
  "/* GENERATED by build.js — do not edit. Source: data/products.json */\n" +
    "window.SGPK_PRODUCTS=" +
    JSON.stringify(JSON.parse(fs.readFileSync(path.join(ROOT, "data", "products.json"), "utf8")).products) +
    ";\n",
  "utf8"
);

/* =========================================================
   CHROME
   ========================================================= */

function buildHeader(page, base) {
  const link = (href, label, key, extra = "") =>
    `<a class="nav__link ${extra} ${page === key ? "is-active" : ""}" href="${base}${href}">${label}</a>`;

  const mega = (cat) => `
    <div class="mega">
      <div class="container mega__inner">
        ${chunk(cat.sub, Math.ceil(cat.sub.length / 3)).map((col) => `
          <div class="mega__col">
            <h4>${esc(cat.label)}</h4>
            ${col.map((s) => `<a href="${base}${cat.page}?sub=${encodeURIComponent(s)}">${esc(s)}</a>`).join("")}
          </div>`).join("")}
        <div class="mega__col">
          <h4>Shop by</h4>
          <a href="${base}new-in.html">New arrivals</a>
          <a href="${base}best-sellers.html">Bestsellers</a>
          <a href="${base}sale.html">On sale</a>
          <a href="${base}${cat.page}">All ${esc(cat.label.toLowerCase())}</a>
        </div>
        <div class="mega__promo">
          <span>Free delivery</span>
          <strong>On every order over Rs. 3,500</strong>
          <p>Cash on delivery available nationwide.</p>
          <a class="viewall" href="${base}${cat.page}">Shop now ${icon("chevronR", 15)}</a>
        </div>
      </div>
    </div>`;

  const catNav = CATEGORIES.filter((c) => c.key !== "tools")
    .map((c) => `<li class="has-mega">${link(c.page, `${c.label} ${icon("chevron", 13, 2)}`, c.key, "nav__chev-wrap")}${mega(c)}</li>`)
    .join("");

  return `
<a class="sr-only" href="#main">Skip to content</a>
<header class="header" id="header">
  <div class="topbar">
    <button class="topbar__nav" id="promoPrev" aria-label="Previous announcement">&#8249;</button>
    <p class="topbar__text" id="promoText">${esc(PROMOS[0])}</p>
    <button class="topbar__nav" id="promoNext" aria-label="Next announcement">&#8250;</button>
  </div>

  <div class="brandtabs">
    <div class="brandtabs__pill">
      <a class="brandtabs__tab is-active" href="${base}index.html">SHEGLAM COSMETICS</a>
      <a class="brandtabs__tab" href="${base}tools.html">TOOLS &amp; SETS</a>
    </div>
  </div>

  <div class="container navbar">
    <button class="hamburger" id="hamburger" aria-label="Open menu" aria-expanded="false">
      <span></span><span></span><span></span>
    </button>

    ${T.logo(base, HAS_LOGO)}

    <nav class="nav" id="nav" aria-label="Primary">
      <ul class="nav__list">
        <li>${link("new-in.html", "New", "new")}</li>
        <li>${link("best-sellers.html", "Best Sellers", "best")}</li>
        ${catNav}
        <li>${link("tools.html", "Tools &amp; Others", "tools")}</li>
        <li>${link("sale.html", "Sale", "sale", "nav__link--sale")}</li>
        <li>${link("collections.html", "Collections", "collections")}</li>
        <li>${link("about.html", "About", "about")}</li>
      </ul>
    </nav>

    <div class="actions">
      <button class="iconbtn" id="searchToggle" aria-label="Search">${icon("search")}</button>
      <div class="region" id="region">
        <button class="iconbtn" id="regionToggle" aria-label="Region and currency">${icon("globe")}</button>
        <div class="region__menu">
          <p>Region</p>
          <button class="is-active">Pakistan &middot; PKR</button>
          <p>Delivery</p>
          <button>Nationwide &middot; 2&ndash;5 days</button>
        </div>
      </div>
      <button class="iconbtn" id="accountBtn" aria-label="Account">${icon("user")}</button>
      <button class="iconbtn" id="wishToggle" aria-label="Wishlist">${icon("heart")}<span class="badge" id="wishCount">0</span></button>
      <button class="iconbtn" id="cartToggle" aria-label="Cart">${icon("cart")}<span class="badge" id="cartCount">0</span></button>
    </div>
  </div>

  <div class="searchbar" id="searchbar" aria-hidden="true">
    <div class="container searchbar__inner">
      <div class="searchbar__field">
        ${icon("search", 19)}
        <input type="search" id="searchInput" placeholder="Search for primer, blush, lip gloss…" aria-label="Search products">
      </div>
      <div class="searchbar__hints">
        <button type="button">primer</button><button type="button">blush</button>
        <button type="button">setting spray</button><button type="button">lip gloss</button>
        <button type="button">concealer</button><button type="button">mascara</button>
      </div>
      <div class="searchres" id="searchRes"></div>
    </div>
  </div>
</header>
<div class="overlay" id="overlay"></div>`;
}

function buildNewsletter(base) {
  return `
<section class="newsletter">
  <div class="container newsletter__inner">
    <h2>Glam With Us</h2>
    <p>Be first to know about new drops, restocks and discounts.</p>
    <form class="newsletter__form" id="newsletterForm" novalidate>
      <input type="email" id="newsletterEmail" placeholder="Enter your email" aria-label="Email address" required>
      <button class="btn" type="submit">Subscribe</button>
    </form>
    <p class="formmsg" id="newsletterMsg" role="status"></p>
    <p class="newsletter__fine">By subscribing you agree to receive marketing emails from ${esc(SITE.name)}.
      You can unsubscribe at any time. See our <a href="${base}privacy.html">Privacy Policy</a>.</p>
  </div>
</section>`;
}

function buildFooter(base) {
  const col = (title, links) => `
    <div>
      <h4>${title}</h4>
      <ul class="footer__links">
        ${links.map((l) => `<li><a href="${base}${l[1]}">${l[0]}</a></li>`).join("")}
      </ul>
    </div>`;

  return `
<footer class="footer">
  <div class="container footer__grid">
    <div class="footer__brand">
      ${T.logo(base, HAS_LOGO)}
      <p>${esc(SITE.tagline)}. Genuine stock, honest prices, cash on delivery nationwide.</p>
      <div class="socials">
        <a href="${SITE.instagram}" target="_blank" rel="noopener" aria-label="Instagram">${brandIcon("instagram")}</a>
        <a href="${SITE.facebook}" target="_blank" rel="noopener" aria-label="Facebook">${brandIcon("facebook")}</a>
        <a href="${SITE.tiktok}" target="_blank" rel="noopener" aria-label="TikTok">${brandIcon("tiktok")}</a>
        <a href="https://wa.me/${SITE.whatsapp}" target="_blank" rel="noopener" aria-label="WhatsApp">${brandIcon("whatsapp")}</a>
      </div>
      <div class="footer__pay">
        <span>Cash on Delivery</span>
      </div>
    </div>
    ${col("Shop", [
      ["New In", "new-in.html"], ["Bestsellers", "best-sellers.html"], ["Face", "face.html"],
      ["Eyes", "eyes.html"], ["Lips", "lips.html"], ["Tools &amp; Others", "tools.html"], ["Sale", "sale.html"],
    ])}
    ${col("Help", [
      ["FAQs", "faq.html"], ["Contact Us", "contact.html"], ["Shipping &amp; Delivery", "shipping.html"],
      ["Returns &amp; Refunds", "returns.html"], ["Shade &amp; Size Guide", "size-guide.html"], ["Track Your Order", "track-order.html"],
    ])}
    ${col("About", [
      ["Our Story", "about.html"], ["Collections", "collections.html"],
      ["Privacy Policy", "privacy.html"], ["Terms &amp; Conditions", "terms.html"],
    ])}
  </div>
  <div class="container footer__bottom">
    <p class="footer__legal">${esc(SITE.disclaimer)}</p>
    <div class="footer__copy">
      <span>&copy; ${new Date().getFullYear()} ${esc(SITE.name)}. All rights reserved.</span>
      <span>${esc(SITE.address)} &middot; <a href="mailto:${SITE.email}">${esc(SITE.email)}</a></span>
    </div>
  </div>
</footer>`;
}

function buildOverlays(base) {
  return `
<aside class="drawer" id="cartDrawer" aria-hidden="true" aria-label="Shopping cart">
  <div class="drawer__head">
    <h3>Your Cart</h3>
    <button class="iconbtn" id="cartClose" aria-label="Close cart">${icon("close", 18)}</button>
  </div>
  <div class="drawer__body" id="cartItems"></div>
  <div class="drawer__foot">
    <p class="drawer__ship" id="cartShipNote"></p>
    <div class="drawer__total"><span>Subtotal</span><strong id="cartSubtotal">Rs. 0</strong></div>
    <button class="btn btn--primary btn--block" id="checkoutBtn" disabled>Checkout</button>
    <a class="btn btn--wa btn--block is-disabled" id="cartWa" target="_blank" rel="noopener">
      ${brandIcon("whatsapp", 18)} Order on WhatsApp</a>
  </div>
</aside>

<aside class="drawer" id="wishDrawer" aria-hidden="true" aria-label="Wishlist">
  <div class="drawer__head">
    <h3>Wishlist</h3>
    <button class="iconbtn" id="wishClose" aria-label="Close wishlist">${icon("close", 18)}</button>
  </div>
  <div class="drawer__body" id="wishItems"></div>
</aside>

<div class="modal" id="quickView" aria-hidden="true" role="dialog" aria-modal="true" aria-label="Quick view">
  <div class="modal__box">
    <button class="modal__x" id="qvClose" aria-label="Close">${icon("close", 16)}</button>
    <div class="modal__scroll" id="qvBody"></div>
  </div>
</div>

<div class="modal" id="checkoutModal" aria-hidden="true" role="dialog" aria-modal="true" aria-labelledby="coTitle">
  <div class="modal__box">
    <button class="modal__x" id="coClose" aria-label="Close checkout">${icon("close", 16)}</button>
    <div class="modal__scroll">
      <div id="coFormState">
        <div class="checkout">
          <div class="checkout__summary">
            <h3>Order Summary</h3>
            <div class="checkout__lines" id="coLines"></div>
            <div class="cototals">
              <div><span>Subtotal</span><span id="coSub">Rs. 0</span></div>
              <div><span>Delivery</span><span id="coShip">Free</span></div>
              <div class="grand"><span>Total</span><span id="coTotal">Rs. 0</span></div>
            </div>
          </div>
          <div class="checkout__form">
            <h3 id="coTitle">Delivery details</h3>
            <p>We deliver nationwide in 2&ndash;5 working days.</p>
            <form id="coForm" novalidate>
              <div class="field">
                <label for="coName">Full name</label>
                <input type="text" id="coName" autocomplete="name" placeholder="e.g. Ayesha Khan">
                <small class="err" data-for="coName"></small>
              </div>
              <div class="field--row">
                <div class="field">
                  <label for="coPhone">Mobile number</label>
                  <input type="tel" id="coPhone" autocomplete="tel" placeholder="0322 0305000">
                  <small class="err" data-for="coPhone"></small>
                </div>
                <div class="field">
                  <label for="coCity">City</label>
                  <input type="text" id="coCity" autocomplete="address-level2" placeholder="Lahore">
                  <small class="err" data-for="coCity"></small>
                </div>
              </div>
              <div class="field">
                <label for="coAddress">Delivery address</label>
                <textarea id="coAddress" rows="3" autocomplete="street-address" placeholder="House / flat, street, area, nearest landmark"></textarea>
                <small class="err" data-for="coAddress"></small>
              </div>
              <div class="field">
                <label for="coEmail">Email <span style="color:var(--menu);font-weight:400">(optional)</span></label>
                <input type="email" id="coEmail" autocomplete="email" placeholder="you@example.com">
                <small class="err" data-for="coEmail"></small>
              </div>
              <div class="field">
                <label for="coNotes">Order notes <span style="color:var(--menu);font-weight:400">(optional)</span></label>
                <textarea id="coNotes" rows="2" placeholder="Anything we should know?"></textarea>
              </div>

              <div class="formerr" id="coError" role="alert" hidden></div>

              <h3 style="margin:22px 0 12px;font-size:15px">Payment method</h3>
              <!-- Cash on delivery is the only method accepted, so this states
                   it rather than offering a choice of one. api/orders.js
                   enforces the same thing server-side. -->
              <div class="radios">
                <div class="radio is-on is-fixed">
                  <span><strong>Cash on Delivery</strong><span>Pay the courier when your parcel arrives. No advance payment, no extra fee.</span></span>
                </div>
              </div>

              <button class="btn btn--primary btn--block btn--lg" type="submit" id="coSubmit">Place order</button>
              <p style="font-size:12.5px;color:var(--muted);margin-top:12px;text-align:center">
                By placing this order you agree to our <a href="${base}terms.html" style="color:var(--rose)">Terms</a>
                and <a href="${base}returns.html" style="color:var(--rose)">Returns Policy</a>.</p>
            </form>
          </div>
        </div>
      </div>

      <div id="coDoneState" style="display:none">
        <div class="confirm">
          <div class="confirm__tick">${icon("check", 30, 2.6)}</div>
          <h3>Order received</h3>
          <p>Thank you! We'll confirm your order on WhatsApp shortly and share tracking once it ships.</p>
          <div class="confirm__ref"><span>Your order reference</span><b id="coRef">SG-0000</b></div>
          <p class="formmsg" id="coWarn" style="display:none;font-size:13.5px;max-width:440px;margin:0 auto 18px;line-height:1.65"></p>
          <div class="confirm__actions">
            <a class="btn btn--wa" id="coWa" target="_blank" rel="noopener">${brandIcon("whatsapp", 18)} Confirm on WhatsApp</a>
            <button class="btn btn--outline" id="coContinue">Continue shopping</button>
          </div>
          <p class="confirm__note">Save your reference — you can look it up any time on the
            <a href="${base}track-order.html" style="color:var(--rose)">Track Order</a> page.</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal" id="reviewModal" aria-hidden="true" role="dialog" aria-modal="true" aria-label="Write a review">
  <div class="modal__box" style="max-width:520px">
    <button class="modal__x" id="rvClose" aria-label="Close">${icon("close", 16)}</button>
    <div class="modal__scroll" style="padding:32px 28px">
      <h3 style="font-size:19px;margin-bottom:6px">Write a review</h3>
      <p style="font-size:13.5px;color:var(--muted);margin-bottom:20px">Only reviews from verified buyers are published.</p>
      <form id="reviewForm" novalidate>
        <div class="field">
          <label>Your rating</label>
          <div class="starpick" id="starpick">
            ${[1, 2, 3, 4, 5].map((n) => `
              <label data-star="${n}" aria-label="${n} star${n > 1 ? "s" : ""}">
                <input type="radio" name="rvStars" value="${n}">
                <span>&#9733;</span>
              </label>`).join("")}
          </div>
        </div>
        <div class="field">
          <label for="rvName">Your name</label>
          <input type="text" id="rvName" placeholder="e.g. Ayesha K.">
        </div>
        <div class="field">
          <label for="rvText">Your review</label>
          <textarea id="rvText" rows="4" placeholder="How did it wear? Would you buy it again?"></textarea>
        </div>
        <button class="btn btn--primary btn--block" type="submit">Submit review</button>
      </form>
    </div>
  </div>
</div>

<a class="wafloat" href="https://wa.me/${SITE.whatsapp}?text=${encodeURIComponent("Hello " + SITE.name + "! I have a question.")}"
   target="_blank" rel="noopener" aria-label="Chat on WhatsApp">${brandIcon("whatsapp", 24)}<span>Chat with us</span></a>
<button class="backtop" id="backTop" aria-label="Back to top">${icon("chevron", 18, 2)}</button>
<div class="toast" id="toast" role="status" aria-live="polite"></div>`;
}

/* =========================================================
   PAGE SHELL
   ========================================================= */
function writePage(o) {
  const base = o.base || "";
  const canonical = SITE.domain + "/" + (o.file === "index.html" ? "" : o.file);
  const ogImage = o.ogImage || PRODUCTS[0].imageLarge;

  const jsonLd = (o.jsonLd || []).map(
    (j) => `<script type="application/ld+json">\n${JSON.stringify(j, null, 2)}\n</script>`
  ).join("\n");

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(o.title)}</title>
<meta name="description" content="${esc(o.description)}">
<link rel="canonical" href="${canonical}">
<meta name="theme-color" content="#e83e70">
<meta property="og:type" content="${o.ogType || "website"}">
<meta property="og:site_name" content="${esc(SITE.name)}">
<meta property="og:title" content="${esc(o.ogTitle || o.title)}">
<meta property="og:description" content="${esc(o.description)}">
<meta property="og:url" content="${canonical}">
<meta property="og:image" content="${ogImage}">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="${FAVICON}">
<link rel="apple-touch-icon" href="${FAVICON}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="preconnect" href="https://images.unsplash.com">
<link rel="stylesheet" href="${FONT}">
<link rel="stylesheet" href="${base}assets/css/style.css">
<script>
/* Which products have real photography. Must load before catalog.js so
   client-side re-renders resolve images the same way the build did. */
window.SGPK_PHOTOS=${JSON.stringify(D.PHOTOS || [])};
/* Registered here, in <head>, so it catches images that fail while the
   page is still parsing — a listener added at end-of-body misses them. */
addEventListener("error",function(e){
  var el=e.target;
  if(!el||el.tagName!=="IMG"||el.dataset.failed)return;
  el.dataset.failed="1";
  if(el.dataset.tile)el.src=el.dataset.tile;
},true);
</script>
${jsonLd}
</head>
<body data-page="${o.page}" data-base="${base}"${o.bodyAttrs || ""}>
${buildHeader(o.page, base)}
<main id="main">
${o.body}
</main>
${o.hideNewsletter ? "" : buildNewsletter(base)}
${buildFooter(base)}
${buildOverlays(base)}
<script src="${base}data/products.js"></script>
<script src="${base}data/catalog.js"></script>
<script src="${base}data/templates.js"></script>
<script src="${base}assets/js/app.js"></script>
<script src="${base}assets/js/catalogue-sync.js" defer></script>
</body>
</html>
`;
  fs.writeFileSync(path.join(ROOT, o.file), html, "utf8");
  return o.file;
}

/* =========================================================
   HELPERS
   ========================================================= */
function chunk(arr, size) {
  const out = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out.filter((c) => c.length);
}

const crumbHTML = (items) => `<div class="container">${T.crumbs(items).replace(' class="crumbs container"', ' class="crumbs"')}</div>`;

function sortControls() {
  return `
  <div class="toolbar">
    <p class="toolbar__left" id="count"></p>
    <div class="toolbar__right">
      <button class="filterbtn" id="filterOpen">${icon("filter", 16)} Filter</button>
      <div class="selectwrap">
        <select id="sortSelect" aria-label="Sort products">
          <option value="recommend">Recommended</option>
          <option value="new">Newest</option>
          <option value="price-asc">Price: low to high</option>
          <option value="price-desc">Price: high to low</option>
          <option value="rating">Top rated</option>
          <option value="discount">Biggest discount</option>
        </select>
        ${icon("chevron", 15)}
      </div>
    </div>
  </div>`;
}

/* Listing page body shared by categories, feeds and collections */
function listingBody(opts) {
  const { title, blurb, crumbs, feed, collection, items, hero } = opts;
  return `
${hero || ""}
${crumbHTML(crumbs)}
<div class="container">
  ${hero ? "" : `<div class="listhead"><h1>${esc(title)}</h1>${blurb ? `<p>${esc(blurb)}</p>` : ""}</div>`}
  <div class="listlayout" id="listing" data-feed="${feed}"${collection ? ` data-collection="${collection}"` : ""}>
    <aside class="filters" id="filters">
      <div class="filters__head">
        <h2>Filter</h2>
        <button class="filters__clear js-clear">Clear all</button>
        <button class="iconbtn" id="filterClose" style="display:none">${icon("close", 18)}</button>
      </div>
      <div id="filterGroups"></div>
      <button class="btn btn--primary btn--block" id="filterDone" style="margin-top:18px">Show results</button>
    </aside>
    <div>
      ${sortControls()}
      <div class="chips" id="chips"></div>
      <div class="grid" id="grid">
        ${items.length
          ? items.map((p) => card(p, "")).join("\n")
          : /* A feed can legitimately be empty — a new shop has no
               bestsellers and nothing reduced yet. Say so and offer a way
               onward, rather than leaving filters above a blank page. */
            `<div class="emptyfeed">
               <p>Nothing here just yet.</p>
               <p class="sub">${esc(opts.emptyNote || "Check back soon — this section fills up as the shop grows.")}</p>
               <a class="btn btn--primary" href="index.html">Browse all products</a>
             </div>`}
      </div>
      <div class="loadmore" id="loadMore" style="display:none">
        <button class="btn btn--outline" id="loadMoreBtn">View more</button>
      </div>
    </div>
  </div>
</div>`;
}

function itemListLd(items, name) {
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    name,
    numberOfItems: items.length,
    itemListElement: items.slice(0, 30).map((p, i) => ({
      "@type": "ListItem",
      position: i + 1,
      url: `${SITE.domain}/product/${p.slug}.html`,
      name: p.name,
    })),
  };
}

function breadcrumbLd(items) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((it, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: it.label,
      item: SITE.domain + "/" + (it.href || "").replace(/^\.\//, ""),
    })),
  };
}

/* =========================================================
   PAGE GENERATORS
   ========================================================= */
const written = [];

/* ---- Home ---- */
written.push(
  writePage({
    file: "index.html",
    page: "home",
    title: `${SITE.name} | Genuine SHEGLAM Makeup in Pakistan — Cash on Delivery`,
    description: `Shop genuine SHEGLAM makeup in Pakistan. Primers, foundation, blush, lip tints and more with cash on delivery nationwide and free shipping over Rs. 3,500.`,
    body: CONTENT.home({ D, T, card, icon, brandIcon, sortControls }),
    jsonLd: [
      {
        "@context": "https://schema.org",
        "@type": "OnlineStore",
        name: SITE.name,
        url: SITE.domain,
        description: SITE.tagline,
        email: SITE.email,
        telephone: SITE.phoneTel,
        address: { "@type": "PostalAddress", addressLocality: "Lahore", addressCountry: "PK" },
        currenciesAccepted: "PKR",
        paymentAccepted: "Cash on Delivery",
        areaServed: "PK",
        sameAs: [SITE.instagram, SITE.facebook, SITE.tiktok],
      },
      {
        "@context": "https://schema.org",
        "@type": "WebSite",
        name: SITE.name,
        url: SITE.domain,
        potentialAction: {
          "@type": "SearchAction",
          target: `${SITE.domain}/search.html?q={search_term_string}`,
          "query-input": "required name=search_term_string",
        },
      },
    ],
  })
);

/* ---- Category pages ---- */
CATEGORIES.forEach((c) => {
  const items = FEEDS[c.key]();
  const crumbs = [{ label: "Home", href: "index.html" }, { label: c.label }];
  written.push(
    writePage({
      file: c.page,
      page: c.key,
      title: `${c.label} Makeup in Pakistan | ${SITE.name}`,
      description: `${c.blurb} Shop ${items.length} genuine SHEGLAM ${c.label.toLowerCase()} products with cash on delivery across Pakistan.`,
      body: listingBody({ title: `${c.label}`, blurb: c.blurb, crumbs, feed: c.key, items }),
      jsonLd: [breadcrumbLd(crumbs.map((x, i) => ({ ...x, href: i ? c.page : "" }))), itemListLd(items, c.label)],
    })
  );
});

/* ---- Feed pages ---- */
[
  { file: "new-in.html", page: "new", feed: "new", title: "New In", blurb: "The latest arrivals, added to the shelf this season." },
  { file: "best-sellers.html", page: "best", feed: "best", title: "Bestsellers", blurb: "The products our customers reorder the most.",
    emptyNote: "We mark bestsellers once real orders start coming in, so this stays honest." },
  { file: "sale.html", page: "sale", feed: "sale", title: "Sale", blurb: "Reduced while stocks last — no code needed.",
    emptyNote: "There are no reductions running at the moment." },
].forEach((f) => {
  const items = FEEDS[f.feed]();
  const crumbs = [{ label: "Home", href: "index.html" }, { label: f.title }];
  written.push(
    writePage({
      file: f.file,
      page: f.page,
      title: `${f.title} | ${SITE.name}`,
      description: `${f.blurb} Genuine SHEGLAM products in Pakistan with cash on delivery.`,
      body: listingBody({ title: f.title, blurb: f.blurb, crumbs, feed: f.feed, items, emptyNote: f.emptyNote }),
      jsonLd: [breadcrumbLd(crumbs.map((x, i) => ({ ...x, href: i ? f.file : "" }))), itemListLd(items, f.title)],
    })
  );
});

/* ---- Collections index ---- */
written.push(
  writePage({
    file: "collections.html",
    page: "collections",
    title: `Collections | ${SITE.name}`,
    description: "Curated SHEGLAM edits — complexion sets, the blush bar, long-wear lips and everything under Rs. 2,000.",
    body: `
${crumbHTML([{ label: "Home", href: "index.html" }, { label: "Collections" }])}
<div class="container">
  <div class="listhead">
    <h1>Collections</h1>
    <p>Edits we have put together so you can shop a whole look instead of hunting product by product.</p>
  </div>
  <div class="colgrid" style="padding-bottom:64px">
    ${COLLECTIONS.map((c) => `
      <a class="colcard" href="${c.page}" style="background:linear-gradient(140deg,${c.tint},${c.tint}cc)">
        <span>${esc(c.sub)}</span>
        <h3>${esc(c.title)}</h3>
        <p>${esc(c.blurb)}</p>
        <em>Shop ${c.ids.length} product${c.ids.length === 1 ? "" : "s"}</em>
      </a>`).join("")}
  </div>
</div>`,
  })
);

/* ---- Collection pages ---- */
COLLECTIONS.forEach((c) => {
  const items = c.ids.map(D.byId).filter(Boolean);
  const crumbs = [{ label: "Home", href: "index.html" }, { label: "Collections", href: "collections.html" }, { label: c.title }];
  const hero = `
  <div class="container" style="padding-top:20px">
    <div class="colhero" style="background:linear-gradient(140deg,${c.tint},${c.tint}cc)">
      <span>${esc(c.sub)}</span>
      <h1>${esc(c.title)}</h1>
      <p>${esc(c.blurb)}</p>
    </div>
  </div>`;
  written.push(
    writePage({
      file: c.page,
      page: "collections",
      title: `${c.title} | ${SITE.name}`,
      description: `${c.blurb} Shop the edit with cash on delivery across Pakistan.`,
      body: listingBody({ title: c.title, crumbs, feed: "collection", collection: c.slug, items, hero }),
      jsonLd: [itemListLd(items, c.title)],
    })
  );
});

/* ---- Search ---- */
written.push(
  writePage({
    file: "search.html",
    page: "search",
    title: `Search | ${SITE.name}`,
    description: "Search the full SHEGLAM PK catalogue by product, category or shade.",
    body: `
${crumbHTML([{ label: "Home", href: "index.html" }, { label: "Search" }])}
<div class="container" style="padding-bottom:64px">
  <div class="listhead">
    <h1 id="searchTitle">Search</h1>
    <p class="listhead__count" id="searchCount"></p>
  </div>
  <form class="searchbar__field" style="max-width:520px;margin-bottom:28px" onsubmit="location.href='search.html?q='+encodeURIComponent(document.getElementById('searchQuery').value);return false;">
    ${icon("search", 19)}
    <input type="search" id="searchQuery" placeholder="Search products…" aria-label="Search products">
  </form>
  <div class="grid" id="searchGrid"></div>
</div>`,
  })
);

/* ---- Product pages ---- */
PRODUCTS.forEach((p) => {
  /* A product whose category was cleared in the admin must not take the
     whole build down — it just loses that breadcrumb. */
  const cat = CATEGORIES.find((c) => c.key === p.category) || null;
  if (!cat) console.warn(`  ! ${p.slug} has no category; its breadcrumb will skip one level.`);
  const related = PRODUCTS.filter((x) => x.category === p.category && x.id !== p.id).slice(0, 5);
  const crumbs = [
    { label: "Home", href: "../index.html" },
    ...(cat ? [{ label: cat.label, href: "../" + cat.page }] : []),
    { label: p.name },
  ];

  // Product pages sit in /product/, so local image paths need the ../ prefix.
  const galleryImgs = p.gallery.map((src) => T.imgSrc(src, "../"));

  const ratingLd = p.reviewCount
    ? { aggregateRating: { "@type": "AggregateRating", ratingValue: p.rating, reviewCount: p.reviewCount } }
    : {};

  const body = `
${crumbHTML(crumbs)}
<div class="container">
  <div class="pdp">
    <div class="gallery">
      <div class="gallery__thumbs">
        ${galleryImgs.map((src, i) => `
          <button class="gallery__thumb ${i === 0 ? "is-on" : ""}" data-full="${src}" aria-label="View image ${i + 1}">
            <img src="${src}" alt="${esc(p.name)} view ${i + 1}" loading="lazy" data-tile="${p.galleryTiles[i]}" data-fallback="${esc(p.name.charAt(0))}">
          </button>`).join("")}
      </div>
      <div class="gallery__main" id="galleryMainWrap">
        <img id="galleryMain" src="${T.imgSrc(p.imageLarge, "../")}" alt="${esc(p.name)}" width="900" height="1035" data-tile="${p.galleryTiles[0]}" data-fallback="${esc(p.name.charAt(0))}">
      </div>
    </div>

    <div class="pdp__info">
      <span class="pdp__cat">${cat ? esc(cat.label) + " &middot; " : ""}${esc(p.sub)}</span>
      <h1 class="pdp__name">${esc(p.name)}</h1>
      <div class="pdp__ratingrow">
        ${p.reviewCount
          ? `${stars(p.rating)} <span>${p.rating}</span> <a href="#reviews">${p.reviewCount} review${p.reviewCount === 1 ? "" : "s"}</a>`
          : `${stars(0)} <a href="#reviews">Be the first to review</a>`}
        <span>&middot;</span><span>SKU ${esc(p.sku)}</span>
      </div>

      <div class="pdp__pricerow">
        <span class="pdp__price">${money(p.price)}</span>
        ${p.oldPrice ? `<span class="pdp__old">${money(p.oldPrice)}</span><span class="pdp__save">-${p.discount}%</span>` : ""}
      </div>
      <p class="pdp__tax">Inclusive of all taxes &middot; ${esc(p.size)} &middot; ${esc(p.finish)} finish</p>

      ${p.shades && p.shades.length ? `
      <div class="optblock" id="shade">
        <div class="optblock__head">
          <span class="optblock__label">Shade: <b id="pdpShadeName">Select a shade</b></span>
          <a class="optblock__guide" href="../size-guide.html">Shade guide</a>
        </div>
        <div class="shades" id="pdpShades">
          ${p.shades.map((s) => `
            <button class="shade ${s.stock ? "" : "is-out"}" data-shade="${esc(s.name)}" style="background:${s.hex}"
                    title="${esc(s.name)}${s.stock ? "" : " — out of stock"}" ${s.stock ? "" : "disabled"}
                    aria-label="${esc(s.name)}"></button>`).join("")}
        </div>
      </div>` : `
      <div class="optblock">
        <div class="optblock__head"><span class="optblock__label">Size: <b>${esc(p.size)}</b></span></div>
        <div class="sizepills"><span class="sizepill is-on">${esc(p.size)}</span></div>
      </div>`}

      <div class="stockline ${p.inStock ? "" : "is-out"}" id="pdpStock">
        <span class="dot"></span><span class="stockline__label">${p.inStock ? "In stock — ships within 1–2 days" : "Out of stock"}</span>
      </div>

      <div class="buyrow">
        <div class="qtybox">
          <button type="button" id="qtyDec" aria-label="Decrease quantity">&minus;</button>
          <input type="number" id="pdpQty" value="1" min="1" max="99" aria-label="Quantity">
          <button type="button" id="qtyInc" aria-label="Increase quantity">+</button>
        </div>
        <button class="btn btn--primary" style="flex:1" id="pdpAdd" ${p.inStock ? "" : "disabled"}>Add to Cart</button>
        <button class="btn btn--outline js-wish" id="pdpWish" data-id="${p.id}" style="flex:none;width:110px">
          ${icon("heart", 16)} <span>Save</span></button>
      </div>
      <button class="btn btn--rose btn--block" id="pdpBuy" ${p.inStock ? "" : "disabled"}>Buy it now</button>
      <a class="btn btn--wa btn--block" id="pdpWa" style="margin-top:10px" target="_blank" rel="noopener"
         href="https://wa.me/${SITE.whatsapp}">${brandIcon("whatsapp", 18)} Order on WhatsApp</a>

      <ul class="trustrow">
        <li>${icon("shield", 18)}<span><b>100% genuine.</b> Sealed stock, batch-checked on arrival.</span></li>
        <li>${icon("truck", 18)}<span><b>Free delivery</b> over Rs. 3,500 — flat Rs. 250 otherwise.</span></li>
        <li>${icon("refresh", 18)}<span><b>7-day returns</b> on unopened items.</span></li>
        <li>${icon("chat", 18)}<span><b>Shade help</b> on WhatsApp before you buy.</span></li>
      </ul>

      <div class="acc" style="margin-top:26px">
        <div class="acc__item is-open">
          <button class="acc__btn" type="button">Description ${icon("plus", 16)}</button>
          <div class="acc__body"><p>${esc(p.desc)}</p></div>
        </div>
        <div class="acc__item">
          <button class="acc__btn" type="button">Details ${icon("plus", 16)}</button>
          <div class="acc__body">
            <dl>
              <dt>Category</dt><dd>${cat ? esc(cat.label) + " &middot; " : ""}${esc(p.sub)}</dd>
              <dt>Finish</dt><dd>${esc(p.finish)}</dd>
              <dt>Size</dt><dd>${esc(p.size)}</dd>
              ${p.shades ? `<dt>Shades</dt><dd>${p.shades.length} available</dd>` : ""}
              <dt>SKU</dt><dd>${esc(p.sku)}</dd>
            </dl>
          </div>
        </div>
        <div class="acc__item">
          <button class="acc__btn" type="button">How to use ${icon("plus", 16)}</button>
          <div class="acc__body">
            <p>Apply to clean, moisturised skin. Build in thin layers rather than one heavy pass, and let each layer settle before adding the next.</p>
            <p>Patch test before first use if you have sensitive skin. Full ingredient lists are printed on the product packaging — message us on WhatsApp if you would like them before ordering.</p>
          </div>
        </div>
        <div class="acc__item">
          <button class="acc__btn" type="button">Delivery &amp; returns ${icon("plus", 16)}</button>
          <div class="acc__body">
            <p>Dispatched within 1&ndash;2 working days. Delivery is 2&ndash;3 days to Lahore, Karachi and Islamabad, and 3&ndash;5 days elsewhere in Pakistan.</p>
            <p>Unopened items can be returned within 7 days. See our <a href="../returns.html">returns policy</a> for the full details.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <section class="reviews" id="reviews">
    <div class="sechead"><div><span class="sechead__tag">Reviews</span><h2 class="sechead__title">Customer reviews</h2></div>
      <button class="btn btn--outline btn--sm" id="rvWrite">Write a review</button></div>

    ${p.reviewCount ? `
    <div class="reviews__top">
      <div class="reviews__score">
        <b>${p.rating}</b>
        ${stars(p.rating)}
        <span>Based on ${p.reviewCount} review${p.reviewCount === 1 ? "" : "s"}</span>
      </div>
      <div class="bars">
        ${[5, 4, 3, 2, 1].map((n) => {
          const c = p.reviews.filter((r) => r.r === n).length;
          const pct = p.reviewCount ? Math.round((c / p.reviewCount) * 100) : 0;
          return `<div class="bar"><span>${n}&#9733;</span>
            <span class="bar__track"><span class="bar__fill" style="width:${pct}%"></span></span>
            <span>${c}</span></div>`;
        }).join("")}
      </div>
    </div>
    <div class="reviews__filters">
      <div class="selectwrap"><select id="rvRating" aria-label="Filter by rating">
        <option value="all">All ratings</option>
        <option value="5">5 stars</option><option value="4">4 stars</option>
        <option value="3">3 stars</option><option value="2">2 stars</option><option value="1">1 star</option>
      </select>${icon("chevron", 15)}</div>
      <div class="selectwrap" style="display:none"><select id="rvShade" aria-label="Filter by shade"></select>${icon("chevron", 15)}</div>
      <div class="selectwrap"><select id="rvSort" aria-label="Sort reviews">
        <option value="recent">Most recent</option>
        <option value="high">Highest rated</option>
        <option value="low">Lowest rated</option>
      </select>${icon("chevron", 15)}</div>
    </div>
    <div class="reviews__list" id="reviewList">
      ${p.reviews.map(T.reviewItem).join("")}
    </div>
    <div class="pager" id="reviewPager"></div>` : `
    <div class="reviews__empty">
      <h3>No reviews yet</h3>
      <p>Bought this? Tell other shoppers how it wore — it genuinely helps.</p>
      <button class="btn btn--primary" onclick="document.getElementById('rvWrite').click()">Write the first review</button>
    </div>
    <div class="reviews__list" id="reviewList" hidden></div>
    <div class="pager" id="reviewPager"></div>`}
  </section>
</div>

<section class="section section--alt">
  <div class="container">
    <div class="sechead"><div><span class="sechead__tag">More from ${esc(cat ? cat.label : p.sub || "the shop")}</span>
      <h2 class="sechead__title">You may also like</h2></div>
      <a class="viewall" href="../${cat ? cat.page : "index.html"}">View all ${icon("chevronR", 15)}</a></div>
    <div class="grid">${related.map((r) => card(r, "../")).join("")}</div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="sechead"><div><h2 class="sechead__title">Recently viewed</h2></div></div>
    <div class="grid" id="recentGrid"></div>
  </div>
</section>`;

  written.push(
    writePage({
      file: path.join("product", p.slug + ".html"),
      page: "product",
      base: "../",
      bodyAttrs: ` data-slug="${p.slug}" data-product-id="${p.id}"`,
      title: `${p.name} — ${cat.label} | ${SITE.name}`,
      description: `Buy the ${p.name} in Pakistan. ${p.desc} ${money(p.price)} with cash on delivery nationwide.`.slice(0, 300),
      ogType: "product",
      ogImage: p.imageLarge,
      body,
      jsonLd: [
        Object.assign({
          "@context": "https://schema.org/",
          "@type": "Product",
          name: p.name,
          image: galleryImgs,
          description: p.desc,
          sku: p.sku,
          brand: { "@type": "Brand", name: "SHEGLAM" },
          category: `${cat.label} > ${p.sub}`,
          offers: {
            "@type": "Offer",
            priceCurrency: "PKR",
            price: p.price,
            availability: p.inStock ? "https://schema.org/InStock" : "https://schema.org/OutOfStock",
            url: `${SITE.domain}/product/${p.slug}.html`,
            seller: { "@type": "Organization", name: SITE.name },
          },
        }, ratingLd),
        breadcrumbLd([
          { label: "Home", href: "" },
          { label: cat.label, href: cat.page },
          { label: p.name, href: `product/${p.slug}.html` },
        ]),
      ],
    })
  );
});

/* ---- Static content pages ---- */
CONTENT.pages({ D, T, icon, brandIcon }).forEach((pg) => {
  written.push(
    writePage({
      file: pg.file,
      page: pg.page,
      title: pg.title,
      description: pg.description,
      body: pg.body,
      jsonLd: pg.jsonLd || [],
      hideNewsletter: pg.hideNewsletter,
    })
  );
});

/* =========================================================
   SITEMAP + ROBOTS
   ========================================================= */
const today = new Date().toISOString().slice(0, 10);
const urls = written
  .map((f) => f.replace(/\\/g, "/"))
  .map((f) => (f === "index.html" ? "" : f))
  .map((f) => ({
    loc: `${SITE.domain}/${f}`,
    pri: f === "" ? "1.0" : f.startsWith("product/") ? "0.8" : "0.7",
  }));

fs.writeFileSync(
  path.join(ROOT, "sitemap.xml"),
  `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url><loc>${u.loc}</loc><lastmod>${today}</lastmod><priority>${u.pri}</priority></url>`).join("\n")}
</urlset>
`,
  "utf8"
);

fs.writeFileSync(
  path.join(ROOT, "robots.txt"),
  `User-agent: *\nAllow: /\n\nSitemap: ${SITE.domain}/sitemap.xml\n`,
  "utf8"
);

console.log(`✓ ${written.length} pages written`);
console.log(`  · ${PRODUCTS.length} products`);
console.log(`  · ${COLLECTIONS.length} collections`);
console.log(`  · sitemap.xml + robots.txt`);
if (!SITE.orderEndpoint) {
  console.log("\n⚠  SITE.orderEndpoint is empty in data/catalog.js");
  console.log("   Orders will NOT be emailed to you — customers must tap WhatsApp.");
}

/* Product photography status */
if (SITE.imageMode === "local") {
  // A product without a photo resolves to an inline studio tile (data: URI)
  const missing = PRODUCTS.filter((p) => /^data:/.test(p.image));
  if (missing.length) {
    console.log(`\n⚠  ${missing.length} of ${PRODUCTS.length} product photos are missing.`);
    console.log("   Those products show a generated studio tile instead.");
    console.log("   Run `node check-images.js` for the full list of filenames.");
  } else {
    console.log(`\n✓ All ${PRODUCTS.length} product photos present.`);
  }
}

const reviewed = PRODUCTS.filter((p) => p.reviewCount).length;
console.log(`\n· ${reviewed} of ${PRODUCTS.length} products have customer reviews.`);
if (!reviewed) {
  console.log("  Reviews are empty — that is correct for a new shop. Add genuine ones to");
  console.log("  REVIEWS in data/catalog.js as customers send them in (README → Getting real reviews).");
}
