/* =========================================================
   SHEGLAM PK — static site generator
   Pre-renders every page (chrome + product grids) so the site
   is fully readable with JavaScript disabled, then writes
   sitemap.xml and robots.txt.

   Run:  node build.js
   ========================================================= */
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const D = require("./data/catalog.js");
const T = require("./data/templates.js");
const CONTENT = require("./src/content.js");

const { SITE, CATEGORIES, PRODUCTS, COLLECTIONS, PROMOS, FEEDS, money } = D;
const { esc, icon, brandIcon, card, stars } = T;

const ROOT = __dirname;
/* Everything this script generates — every page, the sitemap, robots.txt
   and data/products.js — goes into .build/ (gitignored), never the
   project folder: they are build output, made fresh from the database on
   every deploy, not source. deploy-prepare.js copies them into public/.
   Emptied each run, so a page never outlives its product or collection
   (an unpublished product, a renamed or deleted collection). */
const OUT = path.join(ROOT, ".build");
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(path.join(OUT, "product"), { recursive: true });
fs.mkdirSync(path.join(OUT, "data"), { recursive: true });

/* Pages React now renders (app/(shop)/<name>/page.tsx) are not generated
   here; they stay in the sitemap. next.config.ts reads the same folder. */
const SHOP_APP = path.join(ROOT, "app", "(shop)");
const REACT_PAGES = fs.existsSync(SHOP_APP)
  ? fs.readdirSync(SHOP_APP, { withFileTypes: true })
      .filter((e) => e.isDirectory() && /^[a-z0-9-]+$/.test(e.name) && fs.existsSync(path.join(SHOP_APP, e.name, "page.tsx")))
      .map((e) => e.name)
  : [];

const { FONT, FAVICON, TIKTOK_PIXEL, buildHeader, buildNewsletter, buildFooter, buildOverlays, cleanPath, cleanLinks, scriptJson } = require("./data/chrome.js");

/* Products and Settings live in data/products.json (written from the
   database). The browser cannot require JSON, so emit a tiny script that
   hands it the same data. */
const SNAPSHOT = JSON.parse(fs.readFileSync(path.join(ROOT, "data", "products.json"), "utf8"));
fs.writeFileSync(
  path.join(OUT, "data", "products.js"),
  "/* GENERATED by build.js — do not edit. Source: data/products.json */\n" +
    "window.SGPK_SETTINGS=" + JSON.stringify(SNAPSHOT.settings || null) + ";\n" +
    "window.SGPK_COLLECTIONS=" + JSON.stringify(SNAPSHOT.collections || null) + ";\n" +
    "window.SGPK_PRODUCTS=" + JSON.stringify(SNAPSHOT.products) + ";\n",
  "utf8"
);

/* Everything under /assets is served with a one-year immutable cache (see
   vercel.json), so a browser that has a file never asks for it again.
   Each script and stylesheet URL carries a hash of its contents: a changed
   file gets a new URL, and returning visitors get the fix instead of the
   copy they cached before it. */
const version = (rel, dir = ROOT) =>
  crypto.createHash("sha1").update(fs.readFileSync(path.join(dir, rel))).digest("hex").slice(0, 10);
const V = {
  css: version("assets/css/style.css"),
  app: version("assets/js/app.js"),
  products: version("data/products.js", OUT),
  catalog: version("data/catalog.js"),
  templates: version("data/templates.js"),
};

/* =========================================================
   PAGE SHELL
   ========================================================= */
function writePage(o) {
  const base = o.base || "";
  const canonical = SITE.domain + "/" + cleanPath(o.file);
  const ogImage = o.ogImage || PRODUCTS[0].imageLarge;

  const jsonLd = (o.jsonLd || []).map(
    (j) => `<script type="application/ld+json">\n${scriptJson(j, 2)}\n</script>`
  ).join("\n");

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(o.title)}</title>
<meta name="description" content="${esc(o.description)}">
${o.noindex ? `<meta name="robots" content="noindex">` : `<link rel="canonical" href="${canonical}">`}
<meta name="theme-color" content="#e83e70">
<meta property="og:type" content="${o.ogType || "website"}">
<meta property="og:site_name" content="${esc(SITE.name)}">
<meta property="og:title" content="${esc(o.ogTitle || o.title)}">
<meta property="og:description" content="${esc(o.description)}">
<meta property="og:url" content="${canonical}">
<meta property="og:image" content="${ogImage}">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="${FAVICON}">
<link rel="apple-touch-icon" href="${FAVICON}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="preconnect" href="https://images.unsplash.com">
<link rel="stylesheet" href="${FONT}">
<link rel="stylesheet" href="${base}assets/css/style.css?v=${V.css}">
<script>
/* Which products have real photography. Must load before catalog.js so
   client-side re-renders resolve images the same way the build did. */
window.SGPK_PHOTOS=${scriptJson(D.PHOTOS || [])};
/* Registered here, in <head>, so it catches images that fail while the
   page is still parsing — a listener added at end-of-body misses them. */
addEventListener("error",function(e){
  var el=e.target;
  if(!el||el.tagName!=="IMG"||el.dataset.failed)return;
  el.dataset.failed="1";
  if(el.dataset.tile)el.src=el.dataset.tile;
},true);
</script>
${TIKTOK_PIXEL}
${jsonLd}
</head>
<body data-page="${o.page}" data-base="${base}"${o.bodyAttrs || ""}>
${buildHeader(o.page, base)}
<main id="main">
${o.body}
</main>
${o.hideNewsletter ? "" : buildNewsletter(base)}
${buildFooter(base)}
${buildOverlays(base)}
<script src="${base}data/products.js?v=${V.products}"></script>
<script src="${base}data/catalog.js?v=${V.catalog}"></script>
<script src="${base}data/templates.js?v=${V.templates}"></script>
<script src="${base}assets/js/app.js?v=${V.app}"></script>
</body>
</html>
`;
  fs.writeFileSync(path.join(OUT, o.file), cleanLinks(html), "utf8");
  return o.file;
}

/* =========================================================
   HELPERS
   ========================================================= */
const crumbHTML = (items) => `<div class="container">${T.crumbs(items).replace(' class="crumbs container"', ' class="crumbs"')}</div>`;

function sortControls() {
  return `
  <div class="toolbar">
    <p class="toolbar__left" id="count"></p>
    <div class="toolbar__right">
      <button class="filterbtn" id="filterOpen">${icon("filter", 16)} Filter</button>
      <div class="selectwrap">
        <select id="sortSelect" aria-label="Sort products">
          <option value="recommend">Recommended</option>
          <option value="new">Newest</option>
          <option value="price-asc">Price: low to high</option>
          <option value="price-desc">Price: high to low</option>
          <option value="rating">Top rated</option>
          <option value="discount">Biggest discount</option>
        </select>
        ${icon("chevron", 15)}
      </div>
    </div>
  </div>`;
}

/* Listing page body shared by categories, feeds and collections */
function listingBody(opts) {
  const { title, blurb, crumbs, feed, collection, items, hero, sort } = opts;
  return `
${hero || ""}
${crumbHTML(crumbs)}
<div class="container">
  ${hero ? "" : `<div class="listhead"><h1>${esc(title)}</h1>${blurb ? `<p>${esc(blurb)}</p>` : ""}</div>`}
  <div class="listlayout" id="listing" data-feed="${feed}"${collection ? ` data-collection="${collection}"` : ""}${sort ? ` data-sort="${sort}"` : ""}>
    <aside class="filters" id="filters">
      <div class="filters__head">
        <h2>Filter</h2>
        <button class="filters__clear js-clear">Clear all</button>
        <button class="iconbtn" id="filterClose" style="display:none">${icon("close", 18)}</button>
      </div>
      <div id="filterGroups"></div>
      <button class="btn btn--primary btn--block" id="filterDone" style="margin-top:18px">Show results</button>
    </aside>
    <div>
      ${sortControls()}
      <div class="chips" id="chips"></div>
      <div class="grid" id="grid">
        ${items.length
          ? items.map((p) => card(p, "")).join("\n")
          : /* A feed can legitimately be empty — a new shop has no
               bestsellers and nothing reduced yet. Say so and offer a way
               onward, rather than leaving filters above a blank page. */
            `<div class="emptyfeed">
               <p>Nothing here just yet.</p>
               <p class="sub">${esc(opts.emptyNote || "Check back soon — this section fills up as the shop grows.")}</p>
               <a class="btn btn--primary" href="index.html">Browse all products</a>
             </div>`}
      </div>
      <div class="loadmore" id="loadMore" style="display:none">
        <button class="btn btn--outline" id="loadMoreBtn">View more</button>
      </div>
    </div>
  </div>
</div>`;
}

function itemListLd(items, name) {
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    name,
    numberOfItems: items.length,
    itemListElement: items.slice(0, 30).map((p, i) => ({
      "@type": "ListItem",
      position: i + 1,
      url: `${SITE.domain}/product/${p.slug}.html`,
      name: p.name,
    })),
  };
}

function breadcrumbLd(items) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((it, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: it.label,
      item: SITE.domain + "/" + (it.href || "").replace(/^\.\//, ""),
    })),
  };
}

/* =========================================================
   PAGE GENERATORS
   ========================================================= */
const written = [];

/* ---- Home ---- */
written.push(
  writePage({
    file: "index.html",
    page: "home",
    title: `${SITE.name} | Genuine SHEGLAM Makeup in Pakistan — Cash on Delivery`,
    description: `Shop genuine SHEGLAM makeup in Pakistan. Primers, foundation, blush, lip tints and more with cash on delivery nationwide and free shipping over ${money(SITE.freeShippingOver)}.`,
    body: CONTENT.home({ D, T, card, icon, brandIcon, sortControls }),
    jsonLd: [
      {
        "@context": "https://schema.org",
        "@type": "OnlineStore",
        name: SITE.name,
        url: SITE.domain,
        description: SITE.tagline,
        email: SITE.email,
        /* No telephone in the structured data. The number is a WhatsApp
           line, and publishing it as `telephone` invites Google to offer a
           call action that nobody answers. Contact is WhatsApp or email. */
        address: { "@type": "PostalAddress", addressLocality: "Lahore", addressCountry: "PK" },
        currenciesAccepted: "PKR",
        paymentAccepted: "Cash on Delivery",
        areaServed: "PK",
        sameAs: [SITE.instagram, SITE.facebook, SITE.tiktok],
      },
      {
        "@context": "https://schema.org",
        "@type": "WebSite",
        name: SITE.name,
        url: SITE.domain,
        potentialAction: {
          "@type": "SearchAction",
          target: `${SITE.domain}/search.html?q={search_term_string}`,
          "query-input": "required name=search_term_string",
        },
      },
    ],
  })
);

/* ---- Category pages ---- */
CATEGORIES.forEach((c) => {
  const items = FEEDS[c.key]();
  const crumbs = [{ label: "Home", href: "index.html" }, { label: c.label }];
  written.push(
    writePage({
      file: c.page,
      page: c.key,
      title: `${c.label} Makeup in Pakistan | ${SITE.name}`,
      description: `${c.blurb} Shop ${items.length} genuine SHEGLAM ${c.label.toLowerCase()} products with cash on delivery across Pakistan.`,
      body: listingBody({ title: `${c.label}`, blurb: c.blurb, crumbs, feed: c.key, items }),
      jsonLd: [breadcrumbLd(crumbs.map((x, i) => ({ ...x, href: i ? c.page : "" }))), itemListLd(items, c.label)],
    })
  );
});

/* ---- Feed pages ---- */
[
  { file: "new-in.html", page: "new", feed: "new", title: "New In", sort: "new",
    blurb: "The latest arrivals, newest first.",
    emptyNote: "Nothing has been added in the last few weeks — new arrivals appear here as soon as they go on sale." },
  { file: "best-sellers.html", page: "best", feed: "best", title: "Bestsellers", blurb: "The products our customers reorder the most.",
    emptyNote: "We mark bestsellers once real orders start coming in, so this stays honest." },
  { file: "sale.html", page: "sale", feed: "sale", title: "Sale", blurb: "Reduced while stocks last — no code needed.",
    emptyNote: "There are no reductions running at the moment." },
].forEach((f) => {
  const items = FEEDS[f.feed]();
  const crumbs = [{ label: "Home", href: "index.html" }, { label: f.title }];
  written.push(
    writePage({
      file: f.file,
      page: f.page,
      title: `${f.title} | ${SITE.name}`,
      description: `${f.blurb} Genuine SHEGLAM products in Pakistan with cash on delivery.`,
      body: listingBody({ title: f.title, blurb: f.blurb, crumbs, feed: f.feed, items, emptyNote: f.emptyNote, sort: f.sort }),
      jsonLd: [breadcrumbLd(crumbs.map((x, i) => ({ ...x, href: i ? f.file : "" }))), itemListLd(items, f.title)],
    })
  );
});

/* ---- Collections index ---- */
written.push(
  writePage({
    file: "collections.html",
    page: "collections",
    title: `Collections | ${SITE.name}`,
    description: "Curated SHEGLAM edits — complexion sets, the blush bar, long-wear lips and everything under Rs. 2,000.",
    body: `
${crumbHTML([{ label: "Home", href: "index.html" }, { label: "Collections" }])}
<div class="container">
  <div class="listhead">
    <h1>Collections</h1>
    <p>Edits we have put together so you can shop a whole look instead of hunting product by product.</p>
  </div>
  <div class="colgrid" style="padding-bottom:64px">
    ${COLLECTIONS.map((c) => `
      <a class="colcard" href="${c.page}" style="background:linear-gradient(140deg,${c.tint},${c.tint}cc)">
        <span>${esc(c.sub)}</span>
        <h3>${esc(c.title)}</h3>
        <p>${esc(c.blurb)}</p>
        <em>Shop ${c.ids.length} product${c.ids.length === 1 ? "" : "s"}</em>
      </a>`).join("")}
  </div>
</div>`,
  })
);

/* ---- Collection pages ---- */
COLLECTIONS.forEach((c) => {
  const items = c.ids.map(D.byId).filter(Boolean);
  const crumbs = [{ label: "Home", href: "index.html" }, { label: "Collections", href: "collections.html" }, { label: c.title }];
  const hero = `
  <div class="container" style="padding-top:20px">
    <div class="colhero" style="background:linear-gradient(140deg,${c.tint},${c.tint}cc)">
      <span>${esc(c.sub)}</span>
      <h1>${esc(c.title)}</h1>
      <p>${esc(c.blurb)}</p>
    </div>
  </div>`;
  written.push(
    writePage({
      file: c.page,
      page: "collections",
      title: `${c.title} | ${SITE.name}`,
      description: `${c.blurb} Shop the edit with cash on delivery across Pakistan.`,
      body: listingBody({ title: c.title, crumbs, feed: "collection", collection: c.slug, items, hero }),
      jsonLd: [itemListLd(items, c.title)],
    })
  );
});

/* ---- Search ---- */
written.push(
  writePage({
    file: "search.html",
    page: "search",
    title: `Search | ${SITE.name}`,
    description: "Search the full SHEGLAM PK catalogue by product, category or shade.",
    body: `
${crumbHTML([{ label: "Home", href: "index.html" }, { label: "Search" }])}
<div class="container" style="padding-bottom:64px">
  <div class="listhead">
    <h1 id="searchTitle">Search</h1>
    <p class="listhead__count" id="searchCount"></p>
  </div>
  <form class="searchbar__field" style="max-width:520px;margin-bottom:28px" onsubmit="location.href='search?q='+encodeURIComponent(document.getElementById('searchQuery').value);return false;">
    ${icon("search", 19)}
    <input type="search" id="searchQuery" placeholder="Search products…" aria-label="Search products">
  </form>
  <div class="grid" id="searchGrid"></div>
</div>`,
  })
);

/* ---- Product pages ---- */
PRODUCTS.forEach((p) => {
  /* A product whose category was cleared in the admin must not take the
     whole build down — it just loses that breadcrumb. */
  const cat = CATEGORIES.find((c) => c.key === p.category) || null;
  if (!cat) console.warn(`  ! ${p.slug} has no category; its breadcrumb will skip one level.`);
  /* Category, subcategory, size and finish are all optional. Joining only
     the parts that exist avoids lines like "Face · " and
     "Inclusive of all taxes ·  ·  finish". */
  const joined = (parts) => parts.filter(Boolean).map(esc).join(" &middot; ");
  const catLine = joined([cat && cat.label, p.sub]);
  const related = PRODUCTS.filter((x) => x.category === p.category && x.id !== p.id).slice(0, 5);
  const crumbs = [
    { label: "Home", href: "../index.html" },
    ...(cat ? [{ label: cat.label, href: "../" + cat.page }] : []),
    { label: p.name },
  ];

  // Product pages sit in /product/, so local image paths need the ../ prefix.
  const galleryImgs = p.gallery.map((src) => T.imgSrc(src, "../"));

  const ratingLd = p.reviewCount
    ? { aggregateRating: { "@type": "AggregateRating", ratingValue: p.rating, reviewCount: p.reviewCount } }
    : {};

  const body = `
${crumbHTML(crumbs)}
<div class="container">
  <div class="pdp">
    <div class="gallery${galleryImgs.length < 2 ? " gallery--single" : ""}">
      ${/* A strip holding one thumbnail is not a gallery, it is clutter. */ ""}
      ${galleryImgs.length > 1 ? `
      <div class="gallery__thumbs">
        ${galleryImgs.map((src, i) => `
          <button class="gallery__thumb ${i === 0 ? "is-on" : ""}" data-full="${src}" aria-label="View image ${i + 1}">
            <img src="${src}" alt="${esc(p.name)} view ${i + 1}" loading="lazy" data-tile="${p.galleryTiles[i]}" data-fallback="${esc(p.name.charAt(0))}">
          </button>`).join("")}
      </div>` : ""}
      <div class="gallery__main" id="galleryMainWrap">
        <img id="galleryMain" src="${T.imgSrc(p.imageLarge, "../")}" alt="${esc(p.name)}" width="900" height="1035" data-tile="${p.galleryTiles[0]}" data-fallback="${esc(p.name.charAt(0))}">
      </div>
    </div>

    <div class="pdp__info">
      <span class="pdp__cat">${catLine}</span>
      <h1 class="pdp__name">${esc(p.name)}</h1>
      <div class="pdp__ratingrow">
        ${p.reviewCount
          ? `${stars(p.rating)} <span>${p.rating}</span> <a href="#reviews">${p.reviewCount} review${p.reviewCount === 1 ? "" : "s"}</a>`
          : `${stars(0)} <a href="#reviews">Be the first to review</a>`}
        <span>&middot;</span><span>SKU ${esc(p.sku)}</span>
      </div>

      <div class="pdp__pricerow">
        <span class="pdp__price">${money(p.price)}</span>
        ${p.oldPrice ? `<span class="pdp__old">${money(p.oldPrice)}</span><span class="pdp__save">-${p.discount}%</span>` : ""}
      </div>
      <p class="pdp__tax">${joined(["Inclusive of all taxes", p.size, p.finish && p.finish + " finish"])}</p>

      ${p.shades && p.shades.length ? `
      <div class="optblock" id="shade">
        <div class="optblock__head">
          <span class="optblock__label">Shade: <b id="pdpShadeName">Select a shade</b></span>
          <a class="optblock__guide" href="../size-guide.html">Shade guide</a>
        </div>
        <div class="shades" id="pdpShades">
          ${p.shades.map((s) => `
            <button class="shade ${s.stock ? "" : "is-out"}" data-shade="${esc(s.name)}" style="${T.swatchStyle(s, "../")}"
                    title="${esc(s.name)}${s.stock ? "" : " — out of stock"}" ${s.stock ? "" : "disabled"}
                    aria-label="${esc(s.name)}"></button>`).join("")}
        </div>
      </div>` : p.size ? `
      <div class="optblock">
        <div class="optblock__head"><span class="optblock__label">Size: <b>${esc(p.size)}</b></span></div>
        <div class="sizepills"><span class="sizepill is-on">${esc(p.size)}</span></div>
      </div>` : ""}

      <div class="stockline ${p.inStock ? "" : "is-out"}" id="pdpStock">
        <span class="dot"></span><span class="stockline__label">${p.inStock ? "In stock — ships within 1–2 days" : "Out of stock"}</span>
      </div>

      <div class="buyrow">
        <div class="qtybox">
          <button type="button" id="qtyDec" aria-label="Decrease quantity">&minus;</button>
          <input type="number" id="pdpQty" value="1" min="1" max="99" aria-label="Quantity">
          <button type="button" id="qtyInc" aria-label="Increase quantity">+</button>
        </div>
        <button class="btn btn--primary" style="flex:1" id="pdpAdd" ${p.inStock ? "" : "disabled"}>Add to Cart</button>
        <button class="btn btn--outline js-wish" id="pdpWish" data-id="${esc(p.slug)}" style="flex:none;width:110px">
          ${icon("heart", 16)} <span>Save</span></button>
      </div>
      <button class="btn btn--rose btn--block" id="pdpBuy" ${p.inStock ? "" : "disabled"}>Buy it now</button>
      <a class="btn btn--wa btn--block" id="pdpWa" style="margin-top:10px" target="_blank" rel="noopener"
         href="https://wa.me/${SITE.whatsapp}">${brandIcon("whatsapp", 18)} Order on WhatsApp</a>

      <ul class="trustrow">
        <li>${icon("shield", 18)}<span><b>100% genuine.</b> Sealed stock, batch-checked on arrival.</span></li>
        <li>${icon("truck", 18)}<span><b>Free delivery</b> over ${money(SITE.freeShippingOver)} — flat ${money(SITE.flatShipping)} otherwise.</span></li>
        <li>${icon("refresh", 18)}<span><b>${SITE.returnDays}-day returns</b> on unopened items.</span></li>
        <li>${icon("chat", 18)}<span><b>Shade help</b> on WhatsApp before you buy.</span></li>
      </ul>

      <div class="acc" style="margin-top:26px">
        <div class="acc__item is-open">
          <button class="acc__btn" type="button">Description ${icon("plus", 16)}</button>
          <div class="acc__body"><p>${p.desc ? esc(p.desc) : "Message us on WhatsApp for full details of this product before you order."}</p></div>
        </div>
        <div class="acc__item">
          <button class="acc__btn" type="button">Details ${icon("plus", 16)}</button>
          <div class="acc__body">
            <dl>
              ${catLine ? `<dt>Category</dt><dd>${catLine}</dd>` : ""}
              ${p.finish ? `<dt>Finish</dt><dd>${esc(p.finish)}</dd>` : ""}
              ${p.size ? `<dt>Size</dt><dd>${esc(p.size)}</dd>` : ""}
              ${p.shades ? `<dt>Shades</dt><dd>${p.shades.length} available</dd>` : ""}
              <dt>SKU</dt><dd>${esc(p.sku)}</dd>
            </dl>
          </div>
        </div>
        <div class="acc__item">
          <button class="acc__btn" type="button">How to use ${icon("plus", 16)}</button>
          <div class="acc__body">
            <p>Apply to clean, moisturised skin. Build in thin layers rather than one heavy pass, and let each layer settle before adding the next.</p>
            <p>Patch test before first use if you have sensitive skin. Full ingredient lists are printed on the product packaging — message us on WhatsApp if you would like them before ordering.</p>
          </div>
        </div>
        <div class="acc__item">
          <button class="acc__btn" type="button">Delivery &amp; returns ${icon("plus", 16)}</button>
          <div class="acc__body">
            <p>Dispatched within 1&ndash;2 working days. Delivery is 2&ndash;3 days to Lahore, Karachi and Islamabad, and 3&ndash;5 days elsewhere in Pakistan.</p>
            <p>Unopened items can be returned within ${SITE.returnDays} days. See our <a href="../returns.html">returns policy</a> for the full details.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <section class="reviews" id="reviews">
    <div class="sechead"><div><span class="sechead__tag">Reviews</span><h2 class="sechead__title">Customer reviews</h2></div>
      <button class="btn btn--outline btn--sm" id="rvWrite">Write a review</button></div>

    ${p.reviewCount ? `
    <div class="reviews__top">
      <div class="reviews__score">
        <b>${p.rating}</b>
        ${stars(p.rating)}
        <span>Based on ${p.reviewCount} review${p.reviewCount === 1 ? "" : "s"}</span>
      </div>
      <div class="bars">
        ${[5, 4, 3, 2, 1].map((n) => {
          const c = p.reviews.filter((r) => r.r === n).length;
          const pct = p.reviewCount ? Math.round((c / p.reviewCount) * 100) : 0;
          return `<div class="bar"><span>${n}&#9733;</span>
            <span class="bar__track"><span class="bar__fill" style="width:${pct}%"></span></span>
            <span>${c}</span></div>`;
        }).join("")}
      </div>
    </div>
    <div class="reviews__filters">
      <div class="selectwrap"><select id="rvRating" aria-label="Filter by rating">
        <option value="all">All ratings</option>
        <option value="5">5 stars</option><option value="4">4 stars</option>
        <option value="3">3 stars</option><option value="2">2 stars</option><option value="1">1 star</option>
      </select>${icon("chevron", 15)}</div>
      <div class="selectwrap" style="display:none"><select id="rvShade" aria-label="Filter by shade"></select>${icon("chevron", 15)}</div>
      <div class="selectwrap"><select id="rvSort" aria-label="Sort reviews">
        <option value="recent">Most recent</option>
        <option value="high">Highest rated</option>
        <option value="low">Lowest rated</option>
      </select>${icon("chevron", 15)}</div>
    </div>
    <div class="reviews__list" id="reviewList">
      ${p.reviews.map(T.reviewItem).join("")}
    </div>
    <div class="pager" id="reviewPager"></div>` : `
    <div class="reviews__empty">
      <h3>No reviews yet</h3>
      <p>Bought this? Tell other shoppers how it wore — it genuinely helps.</p>
      <button class="btn btn--primary" onclick="document.getElementById('rvWrite').click()">Write the first review</button>
    </div>
    <div class="reviews__list" id="reviewList" hidden></div>
    <div class="pager" id="reviewPager"></div>`}
  </section>
</div>

<section class="section section--alt">
  <div class="container">
    <div class="sechead"><div><span class="sechead__tag">More from ${esc(cat ? cat.label : p.sub || "the shop")}</span>
      <h2 class="sechead__title">You may also like</h2></div>
      <a class="viewall" href="../${cat ? cat.page : "index.html"}">View all ${icon("chevronR", 15)}</a></div>
    <div class="grid">${related.map((r) => card(r, "../")).join("")}</div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="sechead"><div><h2 class="sechead__title">Recently viewed</h2></div></div>
    <div class="grid" id="recentGrid"></div>
  </div>
</section>`;

  written.push(
    writePage({
      file: path.join("product", p.slug + ".html"),
      page: "product",
      base: "../",
      bodyAttrs: ` data-slug="${esc(p.slug)}"`,
      title: `${p.name}${cat ? ` — ${cat.label}` : ""} | ${SITE.name}`,
      description: `Buy the ${p.name} in Pakistan. ${p.desc ? p.desc + " " : ""}${money(p.price)} with cash on delivery nationwide.`.slice(0, 300),
      ogType: "product",
      ogImage: p.imageLarge,
      body,
      jsonLd: [
        Object.assign({
          "@context": "https://schema.org/",
          "@type": "Product",
          name: p.name,
          image: galleryImgs,
          description: p.desc || undefined,
          sku: p.sku,
          brand: { "@type": "Brand", name: "SHEGLAM" },
          category: [cat && cat.label, p.sub].filter(Boolean).join(" > ") || undefined,
          offers: {
            "@type": "Offer",
            priceCurrency: "PKR",
            price: p.price,
            availability: p.inStock ? "https://schema.org/InStock" : "https://schema.org/OutOfStock",
            url: `${SITE.domain}/product/${p.slug}.html`,
            seller: { "@type": "Organization", name: SITE.name },
          },
        }, ratingLd),
        breadcrumbLd([
          { label: "Home", href: "" },
          ...(cat ? [{ label: cat.label, href: cat.page }] : []),
          { label: p.name, href: `product/${p.slug}.html` },
        ]),
      ],
    })
  );
});

/* ---- Content pages (about, contact, faq, …) are React: app/(shop)/<page>/page.tsx ---- */

/* ---- 404 ----
   Vercel serves this for any path with no file. It is not in the sitemap,
   and its links are absolute because it answers at whatever URL was asked
   for.

   A product published a moment ago gets its page once the rebuild that
   publishing started has finished — about a minute. Until then its URL
   lands here, so if the shop already knows the product the page says so
   and opens the product by itself when it is ready. */
writePage({
  file: "404.html",
  page: "notfound",
  base: "/",
  noindex: true,
  hideNewsletter: true,
  title: `Page not found | ${SITE.name}`,
  description: "That page could not be found.",
  body: `
<div class="container">
  <div class="notfound" id="notfound">
    <b>404</b>
    <h1>We couldn't find that page</h1>
    <p>The link may be out of date, or the page may have moved.</p>
    <a class="btn btn--primary" href="/index.html">Back to the shop</a>
  </div>
</div>
<script>
(function () {
  var m = /^\\/product\\/([a-z0-9-]+)(?:\\.html)?$/.exec(location.pathname);
  if (!m) return;
  fetch("/api/products/" + m[1], { headers: { Accept: "application/json" } })
    .then(function (r) { return r.ok ? r.json() : null; })
    .then(function (d) {
      if (!d || !d.product) return;
      var box = document.getElementById("notfound");
      box.innerHTML = "<h1></h1><p>This product has just been added and its page is being prepared. " +
        "It will open here by itself, usually within a minute or two.</p>" +
        '<a class="btn btn--outline" href="/index.html">Keep shopping</a>';
      box.querySelector("h1").textContent = d.product.name;
      var tries = 0;
      (function wait() {
        if (++tries > 40) return;                  // stop after about ten minutes
        setTimeout(function () {
          fetch(location.pathname, { method: "HEAD", cache: "no-store" })
            .then(function (r) { if (r.ok) location.reload(); else wait(); }, wait);
        }, 15000);
      })();
    })
    .catch(function () {});
})();
</script>`,
});

/* =========================================================
   SITEMAP + ROBOTS
   ========================================================= */
const today = new Date().toISOString().slice(0, 10);
const urls = written.concat(REACT_PAGES.map((p) => p + ".html"))
  .map(cleanPath)
  .map((f) => ({
    loc: `${SITE.domain}/${f}`,
    pri: f === "" ? "1.0" : f.startsWith("product/") ? "0.8" : "0.7",
  }));

fs.writeFileSync(
  path.join(OUT, "sitemap.xml"),
  `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url><loc>${u.loc}</loc><lastmod>${today}</lastmod><priority>${u.pri}</priority></url>`).join("\n")}
</urlset>
`,
  "utf8"
);

fs.writeFileSync(
  path.join(OUT, "robots.txt"),
  `User-agent: *\nAllow: /\n\nSitemap: ${SITE.domain}/sitemap.xml\n`,
  "utf8"
);

console.log(`✓ ${written.length} pages written`);
console.log(`  · ${PRODUCTS.length} products`);
console.log(`  · ${COLLECTIONS.length} collections`);
console.log(`  · sitemap.xml + robots.txt`);
/* Product photography status */
if (SITE.imageMode === "local") {
  // A product without a photo resolves to an inline studio tile (data: URI)
  const missing = PRODUCTS.filter((p) => /^data:/.test(p.image));
  if (missing.length) {
    console.log(`\n⚠  ${missing.length} of ${PRODUCTS.length} product photos are missing.`);
    console.log("   Those products show a generated studio tile instead.");
    console.log("   Run `node check-images.js` for the full list of filenames.");
  } else {
    console.log(`\n✓ All ${PRODUCTS.length} product photos present.`);
  }
}

const reviewed = PRODUCTS.filter((p) => p.reviewCount).length;
console.log(`\n· ${reviewed} of ${PRODUCTS.length} products have customer reviews.`);
if (!reviewed) {
  console.log("  Customers' reviews appear once approved in the admin portal (Inbox → Reviews).");
}
