/* =========================================================
   lib/shop.ts — what the React shop pages read, on the server

   The same catalogue (data/catalog.js, built from the database snapshot
   in data/products.json), templates and page chrome (data/chrome.js)
   that build.js uses, so a React page and a generated page show the same
   data and markup. Read at build time: these pages are static.
   ========================================================= */
import type { Metadata } from "next";
import path from "path";

/* eslint-disable @typescript-eslint/no-require-imports */
export const D = require("../data/catalog.js");
export const T = require("../data/templates.js");
export const C = require("../data/chrome.js");
/* eslint-enable @typescript-eslint/no-require-imports */

export const SITE = D.SITE as { domain: string; name: string; email: string; [k: string]: any };

/* Content hashes for the ?v= on scripts and the stylesheet. products.js is
   generated by build.js into public/ before next build runs. */
export const V = {
  css: C.version("assets/css/style.css"),
  app: C.version("assets/js/app.js"),
  catalog: C.version("data/catalog.js"),
  templates: C.version("data/templates.js"),
  products: C.version("data/products.js", path.join(process.cwd(), "public")),
};

/* Title, description, canonical, Open Graph and Twitter tags, as the
   generated pages have them. path is the clean address, e.g. "/privacy". */
export function pageMeta(o: { title: string; description: string; path: string; ogTitle?: string }): Metadata {
  const url = SITE.domain + o.path;
  return {
    title: o.title,
    description: o.description,
    alternates: { canonical: url },
    openGraph: {
      type: "website", siteName: SITE.name, title: o.ogTitle || o.title, description: o.description,
      url, images: [D.PRODUCTS[0] ? D.PRODUCTS[0].imageLarge : undefined].filter(Boolean) as string[],
    },
    twitter: { card: "summary_large_image" },
  };
}
